name: Daily release

on:
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump patch version(true or false)'
        required: false
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: main

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Download Simple Auth bits
        uses: nick-invision/retry@v2
        env:
          SIMPLE_AUTH_SAS_TOKEN: ${{secrets.SIMPLE_AUTH_SAS_TOKEN}}
          SIMPLE_AUTH_ENDPOINT: ${{secrets.SIMPLE_AUTH_ENDPOINT}}
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_on: error
          shell: pwsh
          command: |
            $version=Get-Content packages/fx-core/templates/plugins/resource/simpleauth/version.txt
            $fileName="Microsoft.TeamsFx.SimpleAuth_$version.zip"
            echo $SIMPLE_AUTH_ENDPOINT
            $url=$env:SIMPLE_AUTH_ENDPOINT+'/'+$fileName+'?'+$env:SIMPLE_AUTH_SAS_TOKEN
            Invoke-WebRequest $url -OutFile packages/fx-core/templates/plugins/resource/simpleauth/SimpleAuth.zip

      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'MSFT-yiz'
          git config --global user.email 'yiz@microsoft.com'

      - name: release npm packages to npmjs.org
        if: ${{ github.event_name == 'schedule' || github.event.inputs.bump == 'false' }}
        run: |
          npx lerna publish --no-private --preid=alpha --dist-tag=alpha --yes prerelease

      - name: bump patch version and release npm packages to npmjs.org
        if: ${{ github.event.inputs.bump == 'true' }}
        run: |
          npx lerna publish --no-private --preid=alpha --dist-tag=alpha --yes prepatch --force-publish

      - name: pack vsix
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_on: error
          command: |
            cd ./packages/vscode-extension
            npm install
            npx vsce package

      - name: release VSCode extension to github
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.CD_PAT }}"
          automatic_release_tag: "daily"
          prerelease: true
          files: |
            ./packages/**/*.vsix
