name: Templates Release

on:
  create:

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/templates@') }}
    runs-on: ubuntu-latest
    steps:
    - name: Fetch New Tags
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout Target Tag
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.ref }}
    - name: Generate Template Zip Files
      run: .github/scripts/template-zip-autogen.sh ${{ github.ref }}
    - name: Create Templates Release
      uses: ncipollo/release-action@v1.7.3
      with:
        artifacts: ./*.zip
        name: 'Release for templates ${{ github.ref }}'
        token: ${{ secrets.github_token }}
    - name: Generate Tag List
      run: git tag | grep templates@ > ./template-tags.txt
    - name: Update Template Tag list Release
      uses: ncipollo/release-action@v1.7.3
      with:
        artifacts: ./template-tags.txt
        name: 'Template Tag List'
        body: 'Release to maintain template tag list.'
        token: ${{ secrets.github_token }}
        tag: 'template-tag-list'
        allowUpdates: true
